### PR TITLE
[Merged by Bors] - bevy_ui_exact_image

### PR DESCRIPTION
**Pull request by ickshonpe**

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I'd be interested in seeing this upstreamed at some point :)

bors r+

**Comment by alice-i-cecile** [comment]
bors retry

**Comment by rparrett** [comment]
The asset toml file needs to have a toml extension

**Comment by ickshonpe** [comment]
> The asset toml file needs to have a toml extension
:sweat_smile:

**Comment by rparrett** [comment]
Now it's complaining that the description is too long. (102 chars, max is 100)

(This error message is improved in https://github.com/bevyengine/bevy-website/pull/464)

**Comment by ickshonpe** [comment]
> I'd be interested in seeing this upstreamed at some point :)

still searching for that mythical general implementation that isn't all hacks :pensive:

**Comment by ickshonpe** [comment]
> Now it's complaining that the description is too long. (102 chars, max is 100)
> 
> (This error message is improved in [bevyengine/bevy-website#464](https://github.com/bevyengine/bevy-website/pull/464))

and I fixed that, but deleted a quotation mark while I was there..

**Pull request closed without merging**
