### PR TITLE
[Merged by Bors] - Add `bevy_adventure`

### PR DESCRIPTION
**Pull request by hankjordan**
`bevy_adventure` is a comprehensive framework for building 3d point-and-click adventure games in Bevy.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
The gif is very large: can you use a smaller format?

**Comment by hankjordan** [comment]
> The gif is very large: can you use a smaller format?

Smaller version is 3.9MB via commit #e564ed1

**Comment by mockersf** [comment]
That is still very large... maybe you could shorten it? Maybe removing the few frames in the bathroom scene?

**Comment by hankjordan** [comment]
Reduced asset size to 1.46 MB

**Pull request closed without merging**
