### PR TITLE
Collecting all asset loaders under new category: Asset Loaders

### PR DESCRIPTION
**Pull request by Weibye**
### Issue
Various asset loaders was spread over `3D` and `Helpers` sections creating inconsistency.

### Solution
Move all asset loaders into the new category of `Asset Loaders`

### Unresolved Questions
- I'm a bit unsure if `bevy_prototype_inline_assets` belongs in the `Asset Loader` or `Helpers` sections

### CODE REVIEW

**Comment by Weibye** [comment]
I assume that moving the files to a new folder is all that is required to change the front-end too. If this is not the case, please let me know.

**Comment by mockersf** [comment]
All the asset loader under the 3D section load 3D asset formats, so both before and after your change make sense to me...

The best fix for this would be to change from the single category by asset and to start using tags. This is planned in a (somewhat) near future, but I took a break after the initial migration from Awesome Bevy to Assets to do other things and collect feedback. Other ideas on how to improve the look/feel/usability are welcome, you can see what I plan to do here: https://github.com/bevyengine/bevy-website/issues/159

**Comment by Weibye** [comment]
Yeah good point! 
In that case I'll just leave the PR standing, and instead start poking around with Zola and attempt figuring out support for tags.

**Comment by NiklasEi** [comment]
I think without tags the split to "Asset loaders" is confusing. E.g. "bevy_asset_loader" does not contain an actual Asset loader while some plugins like "bevy_kira_audio" do, but it's not their main functionality.

**Comment by Weibye** [comment]
Closing in favor of migrating to a tag-based system on website

**Pull request closed without merging**
