### PR TITLE
add ascii-bomb-ecs game

### PR DESCRIPTION
**Pull request by aleksa2808**
Adding a game of mine I've ported to rust/bevy a while back and have been using to keep up with bevy updates (I just updated it to bevy 0.11). It comes with a full game lifecycle, from a splash screen, to the menu with persistent togglable options, multiple game modes etc.

### CODE REVIEW

**Comment by mockersf** [comment]
Could you add a license to your repo? Otherwise it can be hard for people to look at the code for examples

**Comment by aleksa2808** [comment]
Sure, I can add it. You mean MIT/Apache2?

Btw, what do you mean when you say it would make it hard for people to look at unlicensed code for learning? Meaning it would be risky to use the code?

**Comment by alice-i-cecile** [comment]
MIT/Apache2 is preferred, but really anything is fine.

The main thing is that otherwise there's no ability to properly reuse even snippets. For any assets that aren't covered, just stick a notice in the README or LICENSE.md about them.

**Comment by aleksa2808** [comment]
Added an MIT license with a disclaimer that it does not cover the assets.
https://github.com/aleksa2808/ascii-bomb-ecs/blob/master/LICENSE.md

**Comment by mockersf** [comment]
thanks!

**Pull request merged**
