### PR TITLE
Add bors config

### PR DESCRIPTION
**Pull request by cart**
The bors app is already set up, but we were missing the config to enable it.

### CODE REVIEW

**Comment by mockersf** [comment]
workflow is only trigger on pull_request events, not push
https://github.com/bevyengine/bevy-assets/blob/94eeb332f6895d92d7b9a9a5e0bb66320bcb0b4b/.github/workflows/ci.yml#L3-L4
so no job is running on bors branch

**Review by mockersf — CHANGES_REQUESTED** [review]
workflow is only triggered on pull_request events, not push
https://github.com/bevyengine/bevy-assets/blob/94eeb332f6895d92d7b9a9a5e0bb66320bcb0b4b/.github/workflows/ci.yml#L3-L4
so no job is running on bors branch

**Comment by cart** [comment]
> (I would close this, but triage team permissions don't extend here)

Arg ill fix this now

**Pull request closed without merging**
