### PR TITLE
Add `crate` field to every crate

### PR DESCRIPTION
**Pull request by benfrankel**
Related to https://github.com/bevyengine/bevy-assets/issues/458.

Also fixes some broken links / renamed crates.

### CODE REVIEW

**Comment by benfrankel** [comment]
The "Unreleased" category (https://github.com/bevyengine/bevy-assets/issues/457) of crates currently have `# TODO: No crate.` in place of a `crate` field in this PR.

**Comment by BD103** [comment]
I'm in favor of this field (and even making it required), but the website will need to be updated in order to handle the new field. Take a look at [`generate-assets`](https://github.com/bevyengine/bevy-website/tree/77625063016f604a02ee04b0f92b14c49abfe38d/generate-assets) for this :)

**Comment by benfrankel** [comment]
Made website PR: https://github.com/bevyengine/bevy-website/pull/1562.

**Review by cart — APPROVED** [review]
I like it!

**Pull request merged**
