### PR TITLE
[Merged by Bors] - Add bevy_spine

### PR DESCRIPTION
**Pull request by jabuwu**
Preview image is almost a megabyte. Let me know if this is too big and I'll make a smaller one.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Larger preview image is more justified here due to need for animation. @IceSentry @mockersf, your opinion?

**Comment by IceSentry** [comment]
I'd suggest using a format other than `.gif`. Gifs aren't particularly efficient compared to other formats like webp. Do you think you could convert your animation to using `webp` instead?

**Review by IceSentry — APPROVED** [review]

**Comment by jabuwu** [comment]
`webp` reduced the size significantly, only about 100kb now 👍

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
