### PR TITLE
[Merged by Bors] - Add image size limit to README.md

### PR DESCRIPTION
**Pull request by hankjordan**
2 MB or less.

~~Also removes gif from image file type suggestion and replaces it with webp.~~

Also adds webp to the image file type suggestions.

### CODE REVIEW

**Review by IceSentry — APPROVED** [review]
I'd keep gif in the list since it's still technically accepted as long as it's small enough.

**Review by alice-i-cecile — APPROVED** [review]

**Comment by alice-i-cecile** [comment]
Ping @mockersf for review.

**Review by mockersf — APPROVED** [review]

**Comment by mockersf** [comment]
Bors r+

**Comment by mockersf** [comment]
I would prefer under 1MB but there's some leeway I guess

**Pull request closed without merging**
