### PR TITLE
[Merged by Bors] - Add bevy-vfx-bag

### PR DESCRIPTION
**Pull request by torsteingrindvik**
Would be nice to use something else than gif but I see there already is some discussion around that, so perhaps in the future.

### CODE REVIEW

**Comment by mockersf** [comment]
Could you try and reduce the gif size? After some small optimisations I was able to reduce the file from 1.7MB to 440KB, feel free to use that one or try your own optimisations

bevy-vfx-bag-smaller

**Comment by torsteingrindvik** [comment]
@mockersf  Thanks, I think yours will work nicely.
Force pushed to use that.

**Pull request closed without merging**
