### PR TITLE
[Merged by Bors] - Add bevy_renet networking asset

### PR DESCRIPTION
**Pull request by lucaspoffo**

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
bors r+

**Comment by mockersf** [comment]
Don't hesitate to cook up a logo or an image for bevy_renet. The asset page will probably change soon to give more place to images

**Comment by lucaspoffo** [comment]
I wish I had a cool logo idea :(

**Comment by mockersf** [comment]
Well if you want bad ideas, Reinette is a kind of apples in French, rainette is a kind of frog, and if it comes to that you can put "renet", "renet network" or other word combinations in dall-e or craiyon for inspiration

**Pull request closed without merging**
