### PR TITLE
[Merged by Bors] - Add `bevy_aabb_instancing`

### PR DESCRIPTION
**Pull request by bonsairobo**

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
@mockersf what's our size limit on assets? Might be nice to reduce the image a bit :)

**Comment by bonsairobo** [comment]
Ah I can try to make a smaller one.

**Comment by mockersf** [comment]
There isn't really a hard size limit, but in this case it should be very easy to reduce a lot, the picture has a big resolution 🙂 

And don't hesitate to use https://tinypng.com to get the best compression you can

**Comment by mockersf** [comment]
@bonsairobo would it be OK to change how the crate is specifying its license? 

You are using the `license-file` field: https://github.com/ForesightMiningSoftwareCorporation/bevy-aabb-instancing/blob/main/Cargo.toml#L7 which according to [cargo docs](https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields) should not be preferred:
> If a package is using a nonstandard license, then the license-file field may be specified in lieu of the license field.
Using this field instead of directly naming the license makes a lot of tooling harder (and won't display the license properly on crates.io, it's currently marked as `non-standard`)

**Comment by mockersf** [comment]
No hurry on Bevy side, whenever the next version will happen is good enough 👍 

Thanks!

**Comment by bonsairobo** [comment]
BTW I pushed a smaller image. Is this ready to merge?

**Pull request closed without merging**
