### PR TITLE
[Merged by Bors] - Pixel Attack

### PR DESCRIPTION
**Pull request by gorkemcnr**
Parallax effect based game written in Rust and Bevy Gaming Engine which uses bevy-parallax

### CODE REVIEW

**Comment by rparrett** [comment]
Could you reduce the image file size? We have a hard 2mb limit, but lower is better if possible.

Here are some image tips:

- An image size with ~400 horizontal pixels should be adequate for most display sizes.
- A 16x9 aspect ratio works best. For 400px width, that's 225px high.
- [gifsicle](https://github.com/kohler/gifsicle) can help optimize gifs
- the webp format is often smaller
- reducing the framerate can help

**Comment by gorkemcnr** [comment]
> 

file size reduced

**Review by alice-i-cecile — APPROVED** [review]

**Review by rparrett — APPROVED** [review]
Thanks!

**Comment by mockersf** [comment]
I reduced it a little more aggressively to get it under 1MB:

pixel-attack

for image resolution, this is still a little bigger than how it will be displayed

**Pull request closed without merging**
