### PR TITLE
update version and license metadata

### PR DESCRIPTION
**Pull request by IceSentry**
In order to show the version and license in the new asset cards we need more metadata 
https://github.com/bevyengine/bevy-website/pull/394

I generated the missing metadata with a quick tool that just reads the github url and tries to parse the Cargo.toml to get the required information. It only works for assets that are actual crates, so it's not perfect but it's better than nothing. The bevy_versions is supposed to be an array for crates that support both a version and main, but I wasn't sure how to detect that information.
https://github.com/IceSentry/bevy_asset_metadata_updater

### CODE REVIEW

**Comment by IceSentry** [comment]
The CI fails because the validation is done with a tool from bevy-website. My PR to bevy-website takes care of that.

**Comment by mockersf** [comment]
I'm not a fan of having this data in this repo as it will need frequent update
* I would prefer to do it at rendering time, so on bevy-website. it would mean it would be updated at least once a day
* if on this repo, could you add a weekly action that would open a PR to update?
* it's also missing all the data from crates.io, see https://github.com/alyti/populate-crate-metadata

> The bevy_versions is supposed to be an array for crates that support both a version and main, but I wasn't sure how to detect that information.

main support should be visible by a git dependency on Bevy. The version was an array also to indicate support for older versions of Bevy

**Comment by IceSentry** [comment]
Sorry, I think I wasn't clear enough about that in my PR.

I agree, this probably should not be done here in the long term. @BlackPhlox is planning to work on making this metadata generation a lot better. I just wanted to have something quickly in order to show something in the assets card as quickly as possible.

I could probably adapt the code to just work with generate-asset on the website and not touch this repo.

> it's also missing all the data from crates.io, see [alyti/populate-crate-metadata](https://github.com/alyti/populate-crate-metadata)

I was only trying to add the data I needed for the new cards. I agree that a final solution should probably load most of cargo's metadata, but I know the cargo team prefers if we don't automatically scrape data and my current approach only uses Cargo.toml

> main support should be visible by a git dependency on Bevy. The version was an array also to indicate support for older versions of Bevy

Yes, that's already what I did, the issue is that I currently only show either a bevy version _or_ "main". This is because I just look at the top level Cargo.toml and there's no way to know both supported version and git dep with that.

**Comment by IceSentry** [comment]
> Even for a bootstrap, I would rather have this repo be just what users actually pushed to it

Makes sense, in that case I'll just close this and try to adapt the generate-assets tool

> The repo I linked is using the sqlite dump of crates.io, that's what the team suggested we use

Sorry, I was a bit too quick on the reply button on that one 😅, I just assumed it was something explaining how to do it.

**Pull request closed without merging**
