### PR TITLE
Add Punchy game

### PR DESCRIPTION
**Pull request by erlend-sh**

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]

**Review by Nilirad — COMMENTED** [review]
Almost 2 MB of gif, can it be reduced?

**Comment by erlend-sh** [comment]
Just did a `.png` instead. Good now?

**Comment by erlend-sh** [comment]
> Almost 2 MB of gif, can it be reduced?

Btw I noticed some entries that already have a 2mb gif. If size is a concern, maybe all games should be static-image only going forward? With time that  page is only going to become increasingly burdensome for low-bandwidth connections.

Allowing looped .mp4s is another option as those are a lot easier to optimize without significant quality loss.

**Comment by alice-i-cecile** [comment]
Yeah; can you make an issue about this please?

**Comment by erlend-sh** [comment]
- https://github.com/bevyengine/bevy-assets/issues/226

**Pull request merged**
