### PR TITLE
Improve the description for Cheatbook

### PR DESCRIPTION
**Pull request by inodentry**

### CODE REVIEW

**Comment by cart** [comment]
Sorry CI failed here when you first submitted it, then I retried a few days ago and it still failed. Trying one more time as I was able to merge a different PR here.

**Comment by cart** [comment]
Eh wait we actually have something to fix here. The new error generator in the website repo is causing issues.

**Comment by cart** [comment]
The issue is fixed, but this needs a rebase to use the new validation logic. I am "hand validating" the text changes instead to save everyone time.

**Comment by mockersf** [comment]
@cart there was another CI issue, as the new description is 127 chars long and we set the limit to 100

**Comment by cart** [comment]
Haha I wish I had read the email notification for this github mention first. I just came to the same conclusion after investigating the failure in the other PR. I'll fix it!

**Pull request merged**
