### PR TITLE
Add bevy_talks with new Dialogues category

### PR DESCRIPTION
**Pull request by giusdp**
Hi,

I added my plugin about `bevy_talks` (about writing dialogue graphs) not really sure what category it would fit so I've created a new "Dialogues" category. Let me know if I need to change it.

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
Hmm. This feels like it belongs in a category that contains localization and things like Yarn/Twine/Inkle integration 🤔

Seems like a sensible grouping, just not sure what to call it.

**Comment by giusdp** [comment]
Yeah I agree. Which name would you suggest? Besides "Dialogues", maybe "Writing", "Narrative", "Storytelling"...? I like Dialogues or Writing personally. I hope there will be other suggestions.

**Comment by alice-i-cecile** [comment]
Dialogues is a bit awkward in English: it implies "a set of conversations", not "tools for writing dialogue". IMO "Writing" or "Dialogue" gets my vote. Either is fine with me; feel free to make the change and I'll merge this in.

**Comment by giusdp** [comment]
Oh ok, got it. I've renamed it to Writing. I feel it's a bit more general that can include any "writing tools" and also because it was the result of a coin flip.

**Review by mockersf — APPROVED** [review]

**Pull request merged**
