### PR TITLE
Add dip to UI asset section

### PR DESCRIPTION
**Pull request by JunichiSugiura**
Hello !
This PR adds two plugins `dip_desktop` and `dip_cli`. dip is aiming to provide missing pieces in Bevy ecosystem to enhance Web3 tech stack. With this in mind, I didn't follow the `bevy_*` convention. I hope it's not confusing !

### CODE REVIEW

**Review by alice-i-cecile — CHANGES_REQUESTED** [review]
It's hard to find the docs for dip_cli / dip_desktop specifically :) Is there a better link / can you make a little README (or docs.rs link) for those?

**Comment by JunichiSugiura** [comment]
Good point. So far, I've only prepared [examples](https://github.com/diptools/dip#desktop-app) in README. I'll come back with docs.

**Comment by alice-i-cecile** [comment]
@JunichiSugiura is this ready to be undrafted now?

**Comment by alice-i-cecile** [comment]
The project hasn't been updated in 3 months; I'm going to close this out for now. Feel free to reopen if you're still interested / resume development.

**Pull request closed without merging**
