### PR TITLE
[Merged by Bors] - Add bevy-kajiya renderer plugin to 3D

### PR DESCRIPTION
**Pull request by seabassjh**

### CODE REVIEW

**Comment by rparrett** [comment]
The screenshot is 2.5mb, could you resize it?

I don't think we have any official guidelines on image size at the moment. I believe they currently aren't displayed any larger than ~200 pixels wide. But a future design that's in the works shows them at something like ~370x168px on mobile displays.

**Comment by seabassjh** [comment]
Alright I have made the image 200px wide

**Comment by mockersf** [comment]
thanks!

**Pull request closed without merging**
