### PR TITLE
Add bevy_generative

### PR DESCRIPTION
**Pull request by manankarnik**
https://github.com/manankarnik/bevy_generative

### CODE REVIEW

**Review by alice-i-cecile — APPROVED** [review]
Cutting it close on the size, but that's fine. You might want to update your README to include more information about the scope / features: the description here was very helpful.

**Comment by manankarnik** [comment]
Alright, I'll add a section in the README for the same. Thanks!

**Comment by mockersf** [comment]
gif can't be optimised by Zola, would you be ok with 
bevy_generative-smaller ? Half the size

**Comment by manankarnik** [comment]
Sure, it would appear rather small on the website either way

**Pull request merged**
