### PR TITLE
[Merged by Bors] - `seldom_*` crates

### PR DESCRIPTION
**Pull request by Seldom-SE**

### CODE REVIEW

**Comment by mockersf** [comment]
please reduce the gif file size 😄

**Comment by Seldom-SE** [comment]
Ok :sweat_smile:

**Comment by mockersf** [comment]
maybe selfom_pixel

**Comment by Seldom-SE** [comment]
> maybe selfom_pixel [ ](https://user-images.githubusercontent.com/8672791/201791837-1a51686e-db73-4981-a3d8-fe26ebfda0b1.gif) selfom_pixel [ ](https://user-images.githubusercontent.com/8672791/201791837-1a51686e-db73-4981-a3d8-fe26ebfda0b1.gif) There are some loss but the file is 577KB instead of 4.91MB slightly_smiling_face

Ah, didn't see this. How's 637 KB?

**Comment by mockersf** [comment]
still on the big side, but why not!

**Review by mockersf — APPROVED** [review]

**Pull request closed without merging**
