### PR TITLE
[Merged by Bors] - add bevy_mod_ui_texture_atlas_image

### PR DESCRIPTION
**Pull request by ickshonpe**

### CODE REVIEW

**Comment by mockersf** [comment]
hello! you should know that your image will be displayed at https://bevyengine.org/assets/, and it currently doesn't have the best ratio

**Comment by ickshonpe** [comment]
> hello! you should know that your image will be displayed at https://bevyengine.org/assets/, and it currently doesn't have the best ratio

Yes, you are right , I changed it.

**Pull request closed without merging**
