### PR TITLE
Super Mario Rust, a bevy game

### PR DESCRIPTION
**Pull request by gorkemcnr**
Super Mario Bros replica. Very short version of Level 1-1 which implements fundamental Bevy usage

### CODE REVIEW

**Comment by alice-i-cecile** [comment]
I'm pretty eh on allowing copyright/trademark infringing games, even if it's clearly a learning exercise.

@cart @mockersf, opinions?

**Comment by mockersf** [comment]
I think this looks too close to the original, in graphics and name...

Nintendo is not known to be friendly to people reusing their characters

**Comment by gorkemcnr** [comment]
Since it was for educational purpose in deed, I am just closing the PR as not sure about "fair usage" policy of Nintendo. So better to close it for now.

**Comment by alice-i-cecile** [comment]
Yep, no worries :) Super cool project, and do repost it if you end up reskinning.

**Comment by cart** [comment]
Yup yall made the right call here. I'd prefer to not be on the Nintendo legal team's radar.

**Pull request closed without merging**
